
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

#  dubbo:
#    scan:
#      # dubbo 服务扫描基准包
#      base-packages: cn.edu.xmu.provider.server
#    protocol:
#      # dubbo 协议
#      name: dubbo
#      # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
#      port: 18889
#    registry:
#      address: nacos://114.215.198.238:8848